CREATE TABLE
    SMPL_PROVINCE
    (
        CODE VARCHAR(255) NOT NULL,
        NAME VARCHAR(255),
        PRIMARY KEY (CODE)
    );
CREATE TABLE
    SMPL_ROLE
    (
        CODE VARCHAR(255) NOT NULL,
        NAME VARCHAR(255),
        PRIMARY KEY (CODE)
    );
CREATE TABLE
    SMPL_USER
    (
        CODE VARCHAR(255) NOT NULL,
        NAME VARCHAR(255),
        EMAIL VARCHAR(255),
        GENDER SMALLINT NOT NULL,
        JOIN_DATE TIMESTAMP,
        LEVEL INTEGER,
        MANAGER SMALLINT NOT NULL,
        MOBILE_NO VARCHAR(255),
        TITLE VARCHAR(255),
        VERSION INTEGER NOT NULL,
        PRVN_CODE VARCHAR(255),
        PRIMARY KEY (CODE),
        CONSTRAINT FKF4BECD14E3DDA82C FOREIGN KEY (PRVN_CODE) REFERENCES SMPL_PROVINCE (CODE)
    );
CREATE TABLE
    SMPL_ORGANIZATION
    (
        CODE VARCHAR(255) NOT NULL,
        NAME VARCHAR(255),
        DISPLAY_NAME VARCHAR(255),
        LEVEL_CODE VARCHAR(255),
        VIRTUAL SMALLINT NOT NULL,
        PARENT VARCHAR(255),
        PRIMARY KEY (CODE),
        CONSTRAINT FK30DF757C2272D867 FOREIGN KEY (PARENT) REFERENCES SMPL_ORGANIZATION (CODE)
    );
CREATE TABLE
    SMPL_USER_ORG
    (
        MANAGER SMALLINT NOT NULL,
        PRIMARY_JOB SMALLINT NOT NULL,
        USER_CODE VARCHAR(255) NOT NULL,
        ORG_CODE VARCHAR(255) NOT NULL,
        PRIMARY KEY (USER_CODE, ORG_CODE),
        CONSTRAINT FKAFD70139A4D71A36 FOREIGN KEY (USER_CODE) REFERENCES SMPL_USER (CODE),
        CONSTRAINT FKAFD70139AC1D3625 FOREIGN KEY (ORG_CODE) REFERENCES SMPL_ORGANIZATION (CODE)
    );
CREATE TABLE
    SMPL_USER_ROLE
    (
        USER_CODE VARCHAR(255) NOT NULL,
        ROLE_NAME VARCHAR(255) NOT NULL,
        PRIMARY KEY (USER_CODE, ROLE_NAME),
        CONSTRAINT FK4B0A78C1A4A519B4 FOREIGN KEY (ROLE_NAME) REFERENCES SMPL_ROLE (CODE),
        CONSTRAINT FK4B0A78C1A4D71A36 FOREIGN KEY (USER_CODE) REFERENCES SMPL_USER (CODE)
    );
CREATE TABLE
    SMPL_ORG_ROLE
    (
        ORG_CODE VARCHAR(255) NOT NULL,
        ROLE_NAME VARCHAR(255) NOT NULL,
        PRIMARY KEY (ORG_CODE, ROLE_NAME),
        CONSTRAINT FKE104DBAA4A519B4 FOREIGN KEY (ROLE_NAME) REFERENCES SMPL_ROLE (CODE),
        CONSTRAINT FKE104DBAAC1D3625 FOREIGN KEY (ORG_CODE) REFERENCES SMPL_ORGANIZATION (CODE)
    );