com.gargoylesoftware.htmlunit.html.HtmlPage htmlPage = (com.gargoylesoftware.htmlunit.html.HtmlPage)map.get("htmlPage");
java.util.List elementList = (java.util.List) htmlPage.getByXPath("//div[@class='cover']/img");
String ret = null;
String url = "http://www.bookabc.net";
if (elementList != null && elementList.size() > 0) {
    com.gargoylesoftware.htmlunit.html.HtmlElement element = elementList.get(0);
    ret = url + element.getAttribute("src");
}
return ret;
