com.gargoylesoftware.htmlunit.html.HtmlPage htmlPage = (com.gargoylesoftware.htmlunit.html.HtmlPage)map.get("htmlPage");
java.util.List elementList = (java.util.List) htmlPage.getByXPath("//p[@class='author']");
String ret = null;
if (elementList != null && elementList.size() > 0) {
    com.gargoylesoftware.htmlunit.html.HtmlElement element = (com.gargoylesoftware.htmlunit.html.HtmlElement)elementList.get(0);
    ret = element.asText().replace("作者：", "");
}
return ret;
