package com.summer.whm.spider.examples.seed;

import java.io.IOException;
import java.net.MalformedURLException;
import java.util.ArrayList;
import java.util.List;

import com.gargoylesoftware.htmlunit.ElementNotFoundException;
import com.gargoylesoftware.htmlunit.FailingHttpStatusCodeException;
import com.gargoylesoftware.htmlunit.html.HtmlAnchor;
import com.gargoylesoftware.htmlunit.html.HtmlPage;
import com.summer.whm.spider.client.WebClientPool;
import com.summer.whm.spider.model.seed.StorySeed;
import com.summer.whm.spider.service.StorySeedService;

public class Bxwx8Spider {
    /**
     * 功能描述: <br>
     * 〈功能详细描述〉
     * 
     * @param args
     * @throws Exception
     * @see [相关类/方法](可选)
     * @since [产品/模块版本](可选)
     */
    public static void main(String[] args) throws Exception {

        String[] urls = new String[] { "http://www.bxwx8.org/btopallvote/0/1.htm",
                "http://www.bxwx8.org/btopallvote/0/2.htm", "http://www.bxwx8.org/btopallvote/0/3.htm",
                "http://www.bxwx8.org/btopallvote/0/4.htm", "http://www.bxwx8.org/btopallvote/0/5.htm",
                "http://www.bxwx8.org/btopallvote/0/6.htm", "http://www.bxwx8.org/btopallvote/0/7.htm",
                "http://www.bxwx8.org/btopallvote/0/8.htm", "http://www.bxwx8.org/btopallvote/0/9.htm",
                "http://www.bxwx8.org/btopallvote/0/10.htm", "http://www.bxwx8.org/btopallvote/0/11.htm",
                "http://www.bxwx8.org/btopallvote/0/12.htm", "http://www.bxwx8.org/btopallvote/0/13.htm",
                "http://www.bxwx8.org/btopallvote/0/14.htm", "http://www.bxwx8.org/btopallvote/0/15.htm",
                "http://www.bxwx8.org/btopallvote/0/16.htm", "http://www.bxwx8.org/btopallvote/0/17.htm",
                "http://www.bxwx8.org/btopallvote/0/18.htm", "http://www.bxwx8.org/btopallvote/0/19.htm",
                "http://www.bxwx8.org/btopallvote/0/20.htm", "http://www.bxwx8.org/btopallvote/0/21.htm",
                "http://www.bxwx8.org/btopallvote/0/22.htm", "http://www.bxwx8.org/btopallvote/0/23.htm",
                "http://www.bxwx8.org/btopallvote/0/24.htm", "http://www.bxwx8.org/btopallvote/0/25.htm",
                "http://www.bxwx8.org/btopallvote/0/26.htm", "http://www.bxwx8.org/btopallvote/0/27.htm",
                "http://www.bxwx8.org/btopallvote/0/28.htm", "http://www.bxwx8.org/btopallvote/0/29.htm",
                "http://www.bxwx8.org/btopallvote/0/30.htm", "http://www.bxwx8.org/btopallvote/0/31.htm",
                "http://www.bxwx8.org/btopallvote/0/32.htm", "http://www.bxwx8.org/btopallvote/0/33.htm",
                "http://www.bxwx8.org/btopallvote/0/34.htm", "http://www.bxwx8.org/btopallvote/0/35.htm",
                "http://www.bxwx8.org/btopallvote/0/36.htm", "http://www.bxwx8.org/btopallvote/0/37.htm",
                "http://www.bxwx8.org/btopallvote/0/38.htm", "http://www.bxwx8.org/btopallvote/0/39.htm",
                "http://www.bxwx8.org/btopallvote/0/40.htm", "http://www.bxwx8.org/btopallvote/0/41.htm",
                "http://www.bxwx8.org/btopallvote/0/42.htm", "http://www.bxwx8.org/btopallvote/0/43.htm",
                "http://www.bxwx8.org/btopallvote/0/44.htm", "http://www.bxwx8.org/btopallvote/0/45.htm",
                "http://www.bxwx8.org/btopallvote/0/46.htm", "http://www.bxwx8.org/btopallvote/0/47.htm",
                "http://www.bxwx8.org/btopallvote/0/48.htm", "http://www.bxwx8.org/btopallvote/0/49.htm",
                "http://www.bxwx8.org/btopallvote/0/50.htm", "http://www.bxwx8.org/btopallvote/0/51.htm",
                "http://www.bxwx8.org/btopallvote/0/52.htm", "http://www.bxwx8.org/btopallvote/0/53.htm",
                "http://www.bxwx8.org/btopallvote/0/54.htm", "http://www.bxwx8.org/btopallvote/0/55.htm",
                "http://www.bxwx8.org/btopallvote/0/56.htm", "http://www.bxwx8.org/btopallvote/0/57.htm",
                "http://www.bxwx8.org/btopallvote/0/58.htm", "http://www.bxwx8.org/btopallvote/0/59.htm",
                "http://www.bxwx8.org/btopallvote/0/60.htm", "http://www.bxwx8.org/btopallvote/0/61.htm",
                "http://www.bxwx8.org/btopallvote/0/62.htm", "http://www.bxwx8.org/btopallvote/0/63.htm",
                "http://www.bxwx8.org/btopallvote/0/64.htm", "http://www.bxwx8.org/btopallvote/0/65.htm",
                "http://www.bxwx8.org/btopallvote/0/66.htm", "http://www.bxwx8.org/btopallvote/0/67.htm",
                "http://www.bxwx8.org/btopallvote/0/68.htm", "http://www.bxwx8.org/btopallvote/0/69.htm",
                "http://www.bxwx8.org/btopallvote/0/70.htm", "http://www.bxwx8.org/btopallvote/0/71.htm",
                "http://www.bxwx8.org/btopallvote/0/72.htm", "http://www.bxwx8.org/btopallvote/0/73.htm",
                "http://www.bxwx8.org/btopallvote/0/74.htm", "http://www.bxwx8.org/btopallvote/0/75.htm",
                "http://www.bxwx8.org/btopallvote/0/76.htm", "http://www.bxwx8.org/btopallvote/0/77.htm",
                "http://www.bxwx8.org/btopallvote/0/78.htm", "http://www.bxwx8.org/btopallvote/0/79.htm",
                "http://www.bxwx8.org/btopallvote/0/80.htm", "http://www.bxwx8.org/btopallvote/0/81.htm",
                "http://www.bxwx8.org/btopallvote/0/82.htm", "http://www.bxwx8.org/btopallvote/0/83.htm",
                "http://www.bxwx8.org/btopallvote/0/84.htm", "http://www.bxwx8.org/btopallvote/0/85.htm",
                "http://www.bxwx8.org/btopallvote/0/86.htm", "http://www.bxwx8.org/btopallvote/0/87.htm",
                "http://www.bxwx8.org/btopallvote/0/88.htm", "http://www.bxwx8.org/btopallvote/0/89.htm",
                "http://www.bxwx8.org/btopallvote/0/90.htm", "http://www.bxwx8.org/btopallvote/0/91.htm",
                "http://www.bxwx8.org/btopallvote/0/92.htm", "http://www.bxwx8.org/btopallvote/0/93.htm",
                "http://www.bxwx8.org/btopallvote/0/94.htm", "http://www.bxwx8.org/btopallvote/0/95.htm",
                "http://www.bxwx8.org/btopallvote/0/96.htm", "http://www.bxwx8.org/btopallvote/0/97.htm",
                "http://www.bxwx8.org/btopallvote/0/98.htm", "http://www.bxwx8.org/btopallvote/0/99.htm",
                "http://www.bxwx8.org/btopallvote/0/100.htm", "http://www.bxwx8.org/btopallvote/0/101.htm",
                "http://www.bxwx8.org/btopallvote/0/102.htm", "http://www.bxwx8.org/btopallvote/0/103.htm",
                "http://www.bxwx8.org/btopallvote/0/104.htm", "http://www.bxwx8.org/btopallvote/0/105.htm",
                "http://www.bxwx8.org/btopallvote/0/106.htm", "http://www.bxwx8.org/btopallvote/0/107.htm",
                "http://www.bxwx8.org/btopallvote/0/108.htm", "http://www.bxwx8.org/btopallvote/0/109.htm",
                "http://www.bxwx8.org/btopallvote/0/110.htm", "http://www.bxwx8.org/btopallvote/0/111.htm",
                "http://www.bxwx8.org/btopallvote/0/112.htm", "http://www.bxwx8.org/btopallvote/0/113.htm",
                "http://www.bxwx8.org/btopallvote/0/114.htm", "http://www.bxwx8.org/btopallvote/0/115.htm",
                "http://www.bxwx8.org/btopallvote/0/116.htm", "http://www.bxwx8.org/btopallvote/0/117.htm",
                "http://www.bxwx8.org/btopallvote/0/118.htm", "http://www.bxwx8.org/btopallvote/0/119.htm",
                "http://www.bxwx8.org/btopallvote/0/120.htm", "http://www.bxwx8.org/btopallvote/0/121.htm",
                "http://www.bxwx8.org/btopallvote/0/122.htm", "http://www.bxwx8.org/btopallvote/0/123.htm",
                "http://www.bxwx8.org/btopallvote/0/124.htm", "http://www.bxwx8.org/btopallvote/0/125.htm",
                "http://www.bxwx8.org/btopallvote/0/126.htm", "http://www.bxwx8.org/btopallvote/0/127.htm",
                "http://www.bxwx8.org/btopallvote/0/128.htm", "http://www.bxwx8.org/btopallvote/0/129.htm",
                "http://www.bxwx8.org/btopallvote/0/130.htm", "http://www.bxwx8.org/btopallvote/0/131.htm",
                "http://www.bxwx8.org/btopallvote/0/132.htm", "http://www.bxwx8.org/btopallvote/0/133.htm",
                "http://www.bxwx8.org/btopallvote/0/134.htm", "http://www.bxwx8.org/btopallvote/0/135.htm",
                "http://www.bxwx8.org/btopallvote/0/136.htm", "http://www.bxwx8.org/btopallvote/0/137.htm",
                "http://www.bxwx8.org/btopallvote/0/138.htm", "http://www.bxwx8.org/btopallvote/0/139.htm",
                "http://www.bxwx8.org/btopallvote/0/140.htm", "http://www.bxwx8.org/btopallvote/0/141.htm",
                "http://www.bxwx8.org/btopallvote/0/142.htm", "http://www.bxwx8.org/btopallvote/0/143.htm",
                "http://www.bxwx8.org/btopallvote/0/144.htm", "http://www.bxwx8.org/btopallvote/0/145.htm",
                "http://www.bxwx8.org/btopallvote/0/146.htm", "http://www.bxwx8.org/btopallvote/0/147.htm",
                "http://www.bxwx8.org/btopallvote/0/148.htm", "http://www.bxwx8.org/btopallvote/0/149.htm",
                "http://www.bxwx8.org/btopallvote/0/150.htm", "http://www.bxwx8.org/btopallvote/0/151.htm",
                "http://www.bxwx8.org/btopallvote/0/152.htm", "http://www.bxwx8.org/btopallvote/0/153.htm",
                "http://www.bxwx8.org/btopallvote/0/154.htm", "http://www.bxwx8.org/btopallvote/0/155.htm",
                "http://www.bxwx8.org/btopallvote/0/156.htm", "http://www.bxwx8.org/btopallvote/0/157.htm",
                "http://www.bxwx8.org/btopallvote/0/158.htm", "http://www.bxwx8.org/btopallvote/0/159.htm",
                "http://www.bxwx8.org/btopallvote/0/160.htm", "http://www.bxwx8.org/btopallvote/0/161.htm",
                "http://www.bxwx8.org/btopallvote/0/162.htm", "http://www.bxwx8.org/btopallvote/0/163.htm",
                "http://www.bxwx8.org/btopallvote/0/164.htm", "http://www.bxwx8.org/btopallvote/0/165.htm",
                "http://www.bxwx8.org/btopallvote/0/166.htm", "http://www.bxwx8.org/btopallvote/0/167.htm",
                "http://www.bxwx8.org/btopallvote/0/168.htm", "http://www.bxwx8.org/btopallvote/0/169.htm",
                "http://www.bxwx8.org/btopallvote/0/170.htm", "http://www.bxwx8.org/btopallvote/0/171.htm",
                "http://www.bxwx8.org/btopallvote/0/172.htm", "http://www.bxwx8.org/btopallvote/0/173.htm",
                "http://www.bxwx8.org/btopallvote/0/174.htm", "http://www.bxwx8.org/btopallvote/0/175.htm",
                "http://www.bxwx8.org/btopallvote/0/176.htm", "http://www.bxwx8.org/btopallvote/0/177.htm",
                "http://www.bxwx8.org/btopallvote/0/178.htm", "http://www.bxwx8.org/btopallvote/0/179.htm",
                "http://www.bxwx8.org/btopallvote/0/180.htm", "http://www.bxwx8.org/btopallvote/0/181.htm",
                "http://www.bxwx8.org/btopallvote/0/182.htm", "http://www.bxwx8.org/btopallvote/0/183.htm",
                "http://www.bxwx8.org/btopallvote/0/184.htm", "http://www.bxwx8.org/btopallvote/0/185.htm",
                "http://www.bxwx8.org/btopallvote/0/186.htm", "http://www.bxwx8.org/btopallvote/0/187.htm",
                "http://www.bxwx8.org/btopallvote/0/188.htm", "http://www.bxwx8.org/btopallvote/0/189.htm",
                "http://www.bxwx8.org/btopallvote/0/190.htm", "http://www.bxwx8.org/btopallvote/0/191.htm",
                "http://www.bxwx8.org/btopallvote/0/192.htm", "http://www.bxwx8.org/btopallvote/0/193.htm",
                "http://www.bxwx8.org/btopallvote/0/194.htm", "http://www.bxwx8.org/btopallvote/0/195.htm",
                "http://www.bxwx8.org/btopallvote/0/196.htm", "http://www.bxwx8.org/btopallvote/0/197.htm",
                "http://www.bxwx8.org/btopallvote/0/198.htm", "http://www.bxwx8.org/btopallvote/0/199.htm",
                "http://www.bxwx8.org/btopallvote/0/200.htm", "http://www.bxwx8.org/btopallvote/0/201.htm",
                "http://www.bxwx8.org/btopallvote/0/202.htm", "http://www.bxwx8.org/btopallvote/0/203.htm",
                "http://www.bxwx8.org/btopallvote/0/204.htm", "http://www.bxwx8.org/btopallvote/0/205.htm",
                "http://www.bxwx8.org/btopallvote/0/206.htm", "http://www.bxwx8.org/btopallvote/0/207.htm",
                "http://www.bxwx8.org/btopallvote/0/208.htm", "http://www.bxwx8.org/btopallvote/0/209.htm",
                "http://www.bxwx8.org/btopallvote/0/210.htm", "http://www.bxwx8.org/btopallvote/0/211.htm",
                "http://www.bxwx8.org/btopallvote/0/212.htm", "http://www.bxwx8.org/btopallvote/0/213.htm",
                "http://www.bxwx8.org/btopallvote/0/214.htm", "http://www.bxwx8.org/btopallvote/0/215.htm",
                "http://www.bxwx8.org/btopallvote/0/216.htm", "http://www.bxwx8.org/btopallvote/0/217.htm",
                "http://www.bxwx8.org/btopallvote/0/218.htm", "http://www.bxwx8.org/btopallvote/0/219.htm",
                "http://www.bxwx8.org/btopallvote/0/220.htm", "http://www.bxwx8.org/btopallvote/0/221.htm",
                "http://www.bxwx8.org/btopallvote/0/222.htm", "http://www.bxwx8.org/btopallvote/0/223.htm",
                "http://www.bxwx8.org/btopallvote/0/224.htm", "http://www.bxwx8.org/btopallvote/0/225.htm",
                "http://www.bxwx8.org/btopallvote/0/226.htm", "http://www.bxwx8.org/btopallvote/0/227.htm",
                "http://www.bxwx8.org/btopallvote/0/228.htm", "http://www.bxwx8.org/btopallvote/0/229.htm",
                "http://www.bxwx8.org/btopallvote/0/230.htm", "http://www.bxwx8.org/btopallvote/0/231.htm",
                "http://www.bxwx8.org/btopallvote/0/232.htm", "http://www.bxwx8.org/btopallvote/0/233.htm",
                "http://www.bxwx8.org/btopallvote/0/234.htm", "http://www.bxwx8.org/btopallvote/0/235.htm",
                "http://www.bxwx8.org/btopallvote/0/236.htm", "http://www.bxwx8.org/btopallvote/0/237.htm",
                "http://www.bxwx8.org/btopallvote/0/238.htm", "http://www.bxwx8.org/btopallvote/0/239.htm",
                "http://www.bxwx8.org/btopallvote/0/240.htm", "http://www.bxwx8.org/btopallvote/0/241.htm",
                "http://www.bxwx8.org/btopallvote/0/242.htm", "http://www.bxwx8.org/btopallvote/0/243.htm",
                "http://www.bxwx8.org/btopallvote/0/244.htm", "http://www.bxwx8.org/btopallvote/0/245.htm",
                "http://www.bxwx8.org/btopallvote/0/246.htm", "http://www.bxwx8.org/btopallvote/0/247.htm",
                "http://www.bxwx8.org/btopallvote/0/248.htm", "http://www.bxwx8.org/btopallvote/0/249.htm",
                "http://www.bxwx8.org/btopallvote/0/250.htm", "http://www.bxwx8.org/btopallvote/0/251.htm",
                "http://www.bxwx8.org/btopallvote/0/252.htm", "http://www.bxwx8.org/btopallvote/0/253.htm",
                "http://www.bxwx8.org/btopallvote/0/254.htm", "http://www.bxwx8.org/btopallvote/0/255.htm",
                "http://www.bxwx8.org/btopallvote/0/256.htm", "http://www.bxwx8.org/btopallvote/0/257.htm",
                "http://www.bxwx8.org/btopallvote/0/258.htm", "http://www.bxwx8.org/btopallvote/0/259.htm",
                "http://www.bxwx8.org/btopallvote/0/260.htm", "http://www.bxwx8.org/btopallvote/0/261.htm",
                "http://www.bxwx8.org/btopallvote/0/262.htm", "http://www.bxwx8.org/btopallvote/0/263.htm",
                "http://www.bxwx8.org/btopallvote/0/264.htm", "http://www.bxwx8.org/btopallvote/0/265.htm",
                "http://www.bxwx8.org/btopallvote/0/266.htm", "http://www.bxwx8.org/btopallvote/0/267.htm",
                "http://www.bxwx8.org/btopallvote/0/268.htm", "http://www.bxwx8.org/btopallvote/0/269.htm",
                "http://www.bxwx8.org/btopallvote/0/270.htm", "http://www.bxwx8.org/btopallvote/0/271.htm",
                "http://www.bxwx8.org/btopallvote/0/272.htm", "http://www.bxwx8.org/btopallvote/0/273.htm",
                "http://www.bxwx8.org/btopallvote/0/274.htm", "http://www.bxwx8.org/btopallvote/0/275.htm",
                "http://www.bxwx8.org/btopallvote/0/276.htm", "http://www.bxwx8.org/btopallvote/0/277.htm",
                "http://www.bxwx8.org/btopallvote/0/278.htm", "http://www.bxwx8.org/btopallvote/0/279.htm",
                "http://www.bxwx8.org/btopallvote/0/280.htm", "http://www.bxwx8.org/btopallvote/0/281.htm",
                "http://www.bxwx8.org/btopallvote/0/282.htm", "http://www.bxwx8.org/btopallvote/0/283.htm",
                "http://www.bxwx8.org/btopallvote/0/284.htm", "http://www.bxwx8.org/btopallvote/0/285.htm",
                "http://www.bxwx8.org/btopallvote/0/286.htm", "http://www.bxwx8.org/btopallvote/0/287.htm",
                "http://www.bxwx8.org/btopallvote/0/288.htm", "http://www.bxwx8.org/btopallvote/0/289.htm",
                "http://www.bxwx8.org/btopallvote/0/290.htm", "http://www.bxwx8.org/btopallvote/0/291.htm",
                "http://www.bxwx8.org/btopallvote/0/292.htm", "http://www.bxwx8.org/btopallvote/0/293.htm",
                "http://www.bxwx8.org/btopallvote/0/294.htm", "http://www.bxwx8.org/btopallvote/0/295.htm",
                "http://www.bxwx8.org/btopallvote/0/296.htm", "http://www.bxwx8.org/btopallvote/0/297.htm",
                "http://www.bxwx8.org/btopallvote/0/298.htm", "http://www.bxwx8.org/btopallvote/0/299.htm",
                "http://www.bxwx8.org/btopallvote/0/300.htm", "http://www.bxwx8.org/btopallvote/0/301.htm",
                "http://www.bxwx8.org/btopallvote/0/302.htm", "http://www.bxwx8.org/btopallvote/0/303.htm",
                "http://www.bxwx8.org/btopallvote/0/304.htm", "http://www.bxwx8.org/btopallvote/0/305.htm",
                "http://www.bxwx8.org/btopallvote/0/306.htm", "http://www.bxwx8.org/btopallvote/0/307.htm",
                "http://www.bxwx8.org/btopallvote/0/308.htm", "http://www.bxwx8.org/btopallvote/0/309.htm",
                "http://www.bxwx8.org/btopallvote/0/310.htm", "http://www.bxwx8.org/btopallvote/0/311.htm",
                "http://www.bxwx8.org/btopallvote/0/312.htm", "http://www.bxwx8.org/btopallvote/0/313.htm",
                "http://www.bxwx8.org/btopallvote/0/314.htm", "http://www.bxwx8.org/btopallvote/0/315.htm",
                "http://www.bxwx8.org/btopallvote/0/316.htm", "http://www.bxwx8.org/btopallvote/0/317.htm",
                "http://www.bxwx8.org/btopallvote/0/318.htm", "http://www.bxwx8.org/btopallvote/0/319.htm",
                "http://www.bxwx8.org/btopallvote/0/320.htm", "http://www.bxwx8.org/btopallvote/0/321.htm",
                "http://www.bxwx8.org/btopallvote/0/322.htm", "http://www.bxwx8.org/btopallvote/0/323.htm",
                "http://www.bxwx8.org/btopallvote/0/324.htm", "http://www.bxwx8.org/btopallvote/0/325.htm",
                "http://www.bxwx8.org/btopallvote/0/326.htm", "http://www.bxwx8.org/btopallvote/0/327.htm",
                "http://www.bxwx8.org/btopallvote/0/328.htm", "http://www.bxwx8.org/btopallvote/0/329.htm",
                "http://www.bxwx8.org/btopallvote/0/330.htm", "http://www.bxwx8.org/btopallvote/0/331.htm",
                "http://www.bxwx8.org/btopallvote/0/332.htm", "http://www.bxwx8.org/btopallvote/0/333.htm",
                "http://www.bxwx8.org/btopallvote/0/334.htm", "http://www.bxwx8.org/btopallvote/0/335.htm",
                "http://www.bxwx8.org/btopallvote/0/336.htm", "http://www.bxwx8.org/btopallvote/0/337.htm",
                "http://www.bxwx8.org/btopallvote/0/338.htm", "http://www.bxwx8.org/btopallvote/0/339.htm",
                "http://www.bxwx8.org/btopallvote/0/340.htm", "http://www.bxwx8.org/btopallvote/0/341.htm",
                "http://www.bxwx8.org/btopallvote/0/342.htm", "http://www.bxwx8.org/btopallvote/0/343.htm",
                "http://www.bxwx8.org/btopallvote/0/344.htm", "http://www.bxwx8.org/btopallvote/0/345.htm",
                "http://www.bxwx8.org/btopallvote/0/346.htm", "http://www.bxwx8.org/btopallvote/0/347.htm",
                "http://www.bxwx8.org/btopallvote/0/348.htm", "http://www.bxwx8.org/btopallvote/0/349.htm",
                "http://www.bxwx8.org/btopallvote/0/350.htm", "http://www.bxwx8.org/btopallvote/0/351.htm",
                "http://www.bxwx8.org/btopallvote/0/352.htm", "http://www.bxwx8.org/btopallvote/0/353.htm",
                "http://www.bxwx8.org/btopallvote/0/354.htm", "http://www.bxwx8.org/btopallvote/0/355.htm",
                "http://www.bxwx8.org/btopallvote/0/356.htm", "http://www.bxwx8.org/btopallvote/0/357.htm",
                "http://www.bxwx8.org/btopallvote/0/358.htm", "http://www.bxwx8.org/btopallvote/0/359.htm",
                "http://www.bxwx8.org/btopallvote/0/360.htm", "http://www.bxwx8.org/btopallvote/0/361.htm",
                "http://www.bxwx8.org/btopallvote/0/362.htm", "http://www.bxwx8.org/btopallvote/0/363.htm",
                "http://www.bxwx8.org/btopallvote/0/364.htm", "http://www.bxwx8.org/btopallvote/0/365.htm",
                "http://www.bxwx8.org/btopallvote/0/366.htm", "http://www.bxwx8.org/btopallvote/0/367.htm",
                "http://www.bxwx8.org/btopallvote/0/368.htm", "http://www.bxwx8.org/btopallvote/0/369.htm",
                "http://www.bxwx8.org/btopallvote/0/370.htm", "http://www.bxwx8.org/btopallvote/0/371.htm",
                "http://www.bxwx8.org/btopallvote/0/372.htm", "http://www.bxwx8.org/btopallvote/0/373.htm",
                "http://www.bxwx8.org/btopallvote/0/374.htm", "http://www.bxwx8.org/btopallvote/0/375.htm",
                "http://www.bxwx8.org/btopallvote/0/376.htm", "http://www.bxwx8.org/btopallvote/0/377.htm",
                "http://www.bxwx8.org/btopallvote/0/378.htm", "http://www.bxwx8.org/btopallvote/0/379.htm",
                "http://www.bxwx8.org/btopallvote/0/380.htm", "http://www.bxwx8.org/btopallvote/0/381.htm",
                "http://www.bxwx8.org/btopallvote/0/382.htm", "http://www.bxwx8.org/btopallvote/0/383.htm",
                "http://www.bxwx8.org/btopallvote/0/384.htm", "http://www.bxwx8.org/btopallvote/0/385.htm",
                "http://www.bxwx8.org/btopallvote/0/386.htm", "http://www.bxwx8.org/btopallvote/0/387.htm",
                "http://www.bxwx8.org/btopallvote/0/388.htm", "http://www.bxwx8.org/btopallvote/0/389.htm",
                "http://www.bxwx8.org/btopallvote/0/390.htm", "http://www.bxwx8.org/btopallvote/0/391.htm",
                "http://www.bxwx8.org/btopallvote/0/392.htm", "http://www.bxwx8.org/btopallvote/0/393.htm",
                "http://www.bxwx8.org/btopallvote/0/394.htm", "http://www.bxwx8.org/btopallvote/0/395.htm",
                "http://www.bxwx8.org/btopallvote/0/396.htm", "http://www.bxwx8.org/btopallvote/0/397.htm",
                "http://www.bxwx8.org/btopallvote/0/398.htm", "http://www.bxwx8.org/btopallvote/0/399.htm",
                "http://www.bxwx8.org/btopallvote/0/400.htm", "http://www.bxwx8.org/btopallvote/0/401.htm",
                "http://www.bxwx8.org/btopallvote/0/402.htm", "http://www.bxwx8.org/btopallvote/0/403.htm",
                "http://www.bxwx8.org/btopallvote/0/404.htm", "http://www.bxwx8.org/btopallvote/0/405.htm",
                "http://www.bxwx8.org/btopallvote/0/406.htm", "http://www.bxwx8.org/btopallvote/0/407.htm",
                "http://www.bxwx8.org/btopallvote/0/408.htm", "http://www.bxwx8.org/btopallvote/0/409.htm",
                "http://www.bxwx8.org/btopallvote/0/410.htm", "http://www.bxwx8.org/btopallvote/0/411.htm",
                "http://www.bxwx8.org/btopallvote/0/412.htm", "http://www.bxwx8.org/btopallvote/0/413.htm",
                "http://www.bxwx8.org/btopallvote/0/414.htm", "http://www.bxwx8.org/btopallvote/0/415.htm",
                "http://www.bxwx8.org/btopallvote/0/416.htm", "http://www.bxwx8.org/btopallvote/0/417.htm",
                "http://www.bxwx8.org/btopallvote/0/418.htm", "http://www.bxwx8.org/btopallvote/0/419.htm",
                "http://www.bxwx8.org/btopallvote/0/420.htm", "http://www.bxwx8.org/btopallvote/0/421.htm",
                "http://www.bxwx8.org/btopallvote/0/422.htm", "http://www.bxwx8.org/btopallvote/0/423.htm",
                "http://www.bxwx8.org/btopallvote/0/424.htm", "http://www.bxwx8.org/btopallvote/0/425.htm",
                "http://www.bxwx8.org/btopallvote/0/426.htm", "http://www.bxwx8.org/btopallvote/0/427.htm",
                "http://www.bxwx8.org/btopallvote/0/428.htm", "http://www.bxwx8.org/btopallvote/0/429.htm",
                "http://www.bxwx8.org/btopallvote/0/430.htm", "http://www.bxwx8.org/btopallvote/0/431.htm",
                "http://www.bxwx8.org/btopallvote/0/432.htm", "http://www.bxwx8.org/btopallvote/0/433.htm",
                "http://www.bxwx8.org/btopallvote/0/434.htm", "http://www.bxwx8.org/btopallvote/0/435.htm",
                "http://www.bxwx8.org/btopallvote/0/436.htm", "http://www.bxwx8.org/btopallvote/0/437.htm",
                "http://www.bxwx8.org/btopallvote/0/438.htm", "http://www.bxwx8.org/btopallvote/0/439.htm",
                "http://www.bxwx8.org/btopallvote/0/440.htm", "http://www.bxwx8.org/btopallvote/0/441.htm",
                "http://www.bxwx8.org/btopallvote/0/442.htm", "http://www.bxwx8.org/btopallvote/0/443.htm",
                "http://www.bxwx8.org/btopallvote/0/444.htm", "http://www.bxwx8.org/btopallvote/0/445.htm",
                "http://www.bxwx8.org/btopallvote/0/446.htm", "http://www.bxwx8.org/btopallvote/0/447.htm",
                "http://www.bxwx8.org/btopallvote/0/448.htm", "http://www.bxwx8.org/btopallvote/0/449.htm",
                "http://www.bxwx8.org/btopallvote/0/450.htm", "http://www.bxwx8.org/btopallvote/0/451.htm",
                "http://www.bxwx8.org/btopallvote/0/452.htm", "http://www.bxwx8.org/btopallvote/0/453.htm",
                "http://www.bxwx8.org/btopallvote/0/454.htm", "http://www.bxwx8.org/btopallvote/0/455.htm",
                "http://www.bxwx8.org/btopallvote/0/456.htm", "http://www.bxwx8.org/btopallvote/0/457.htm",
                "http://www.bxwx8.org/btopallvote/0/458.htm", "http://www.bxwx8.org/btopallvote/0/459.htm",
                "http://www.bxwx8.org/btopallvote/0/460.htm", "http://www.bxwx8.org/btopallvote/0/461.htm",
                "http://www.bxwx8.org/btopallvote/0/462.htm", "http://www.bxwx8.org/btopallvote/0/463.htm",
                "http://www.bxwx8.org/btopallvote/0/464.htm", "http://www.bxwx8.org/btopallvote/0/465.htm",
                "http://www.bxwx8.org/btopallvote/0/466.htm", "http://www.bxwx8.org/btopallvote/0/467.htm",
                "http://www.bxwx8.org/btopallvote/0/468.htm", "http://www.bxwx8.org/btopallvote/0/469.htm",
                "http://www.bxwx8.org/btopallvote/0/470.htm", "http://www.bxwx8.org/btopallvote/0/471.htm",
                "http://www.bxwx8.org/btopallvote/0/472.htm", "http://www.bxwx8.org/btopallvote/0/473.htm",
                "http://www.bxwx8.org/btopallvote/0/474.htm", "http://www.bxwx8.org/btopallvote/0/475.htm",
                "http://www.bxwx8.org/btopallvote/0/476.htm", "http://www.bxwx8.org/btopallvote/0/477.htm",
                "http://www.bxwx8.org/btopallvote/0/478.htm", "http://www.bxwx8.org/btopallvote/0/479.htm",
                "http://www.bxwx8.org/btopallvote/0/480.htm", "http://www.bxwx8.org/btopallvote/0/481.htm",
                "http://www.bxwx8.org/btopallvote/0/482.htm", "http://www.bxwx8.org/btopallvote/0/483.htm",
                "http://www.bxwx8.org/btopallvote/0/484.htm", "http://www.bxwx8.org/btopallvote/0/485.htm",
                "http://www.bxwx8.org/btopallvote/0/486.htm", "http://www.bxwx8.org/btopallvote/0/487.htm",
                "http://www.bxwx8.org/btopallvote/0/488.htm", "http://www.bxwx8.org/btopallvote/0/489.htm",
                "http://www.bxwx8.org/btopallvote/0/490.htm", "http://www.bxwx8.org/btopallvote/0/491.htm",
                "http://www.bxwx8.org/btopallvote/0/492.htm", "http://www.bxwx8.org/btopallvote/0/493.htm",
                "http://www.bxwx8.org/btopallvote/0/494.htm", "http://www.bxwx8.org/btopallvote/0/495.htm",
                "http://www.bxwx8.org/btopallvote/0/496.htm", "http://www.bxwx8.org/btopallvote/0/497.htm",
                "http://www.bxwx8.org/btopallvote/0/498.htm", "http://www.bxwx8.org/btopallvote/0/499.htm",
                "http://www.bxwx8.org/btopallvote/0/500.htm", "http://www.bxwx8.org/btopallvote/0/501.htm",
                "http://www.bxwx8.org/btopallvote/0/502.htm", "http://www.bxwx8.org/btopallvote/0/503.htm",
                "http://www.bxwx8.org/btopallvote/0/504.htm", "http://www.bxwx8.org/btopallvote/0/505.htm",
                "http://www.bxwx8.org/btopallvote/0/506.htm", "http://www.bxwx8.org/btopallvote/0/507.htm",
                "http://www.bxwx8.org/btopallvote/0/508.htm", "http://www.bxwx8.org/btopallvote/0/509.htm",
                "http://www.bxwx8.org/btopallvote/0/510.htm", "http://www.bxwx8.org/btopallvote/0/511.htm",
                "http://www.bxwx8.org/btopallvote/0/512.htm", "http://www.bxwx8.org/btopallvote/0/513.htm",
                "http://www.bxwx8.org/btopallvote/0/514.htm", "http://www.bxwx8.org/btopallvote/0/515.htm",
                "http://www.bxwx8.org/btopallvote/0/516.htm", "http://www.bxwx8.org/btopallvote/0/517.htm",
                "http://www.bxwx8.org/btopallvote/0/518.htm", "http://www.bxwx8.org/btopallvote/0/519.htm",
                "http://www.bxwx8.org/btopallvote/0/520.htm", "http://www.bxwx8.org/btopallvote/0/521.htm",
                "http://www.bxwx8.org/btopallvote/0/522.htm", "http://www.bxwx8.org/btopallvote/0/523.htm",
                "http://www.bxwx8.org/btopallvote/0/524.htm", "http://www.bxwx8.org/btopallvote/0/525.htm",
                "http://www.bxwx8.org/btopallvote/0/526.htm", "http://www.bxwx8.org/btopallvote/0/527.htm",
                "http://www.bxwx8.org/btopallvote/0/528.htm", "http://www.bxwx8.org/btopallvote/0/529.htm",
                "http://www.bxwx8.org/btopallvote/0/530.htm", "http://www.bxwx8.org/btopallvote/0/531.htm",
                "http://www.bxwx8.org/btopallvote/0/532.htm", "http://www.bxwx8.org/btopallvote/0/533.htm",
                "http://www.bxwx8.org/btopallvote/0/534.htm", "http://www.bxwx8.org/btopallvote/0/535.htm",
                "http://www.bxwx8.org/btopallvote/0/536.htm", "http://www.bxwx8.org/btopallvote/0/537.htm",
                "http://www.bxwx8.org/btopallvote/0/538.htm", "http://www.bxwx8.org/btopallvote/0/539.htm",
                "http://www.bxwx8.org/btopallvote/0/540.htm", "http://www.bxwx8.org/btopallvote/0/541.htm",
                "http://www.bxwx8.org/btopallvote/0/542.htm", "http://www.bxwx8.org/btopallvote/0/543.htm",
                "http://www.bxwx8.org/btopallvote/0/544.htm", "http://www.bxwx8.org/btopallvote/0/545.htm",
                "http://www.bxwx8.org/btopallvote/0/546.htm", "http://www.bxwx8.org/btopallvote/0/547.htm",
                "http://www.bxwx8.org/btopallvote/0/548.htm", "http://www.bxwx8.org/btopallvote/0/549.htm",
                "http://www.bxwx8.org/btopallvote/0/550.htm", "http://www.bxwx8.org/btopallvote/0/551.htm",
                "http://www.bxwx8.org/btopallvote/0/552.htm", "http://www.bxwx8.org/btopallvote/0/553.htm",
                "http://www.bxwx8.org/btopallvote/0/554.htm", "http://www.bxwx8.org/btopallvote/0/555.htm",
                "http://www.bxwx8.org/btopallvote/0/556.htm", "http://www.bxwx8.org/btopallvote/0/557.htm",
                "http://www.bxwx8.org/btopallvote/0/558.htm", "http://www.bxwx8.org/btopallvote/0/559.htm",
                "http://www.bxwx8.org/btopallvote/0/560.htm", "http://www.bxwx8.org/btopallvote/0/561.htm",
                "http://www.bxwx8.org/btopallvote/0/562.htm", "http://www.bxwx8.org/btopallvote/0/563.htm",
                "http://www.bxwx8.org/btopallvote/0/564.htm", "http://www.bxwx8.org/btopallvote/0/565.htm",
                "http://www.bxwx8.org/btopallvote/0/566.htm", "http://www.bxwx8.org/btopallvote/0/567.htm",
                "http://www.bxwx8.org/btopallvote/0/568.htm", "http://www.bxwx8.org/btopallvote/0/569.htm",
                "http://www.bxwx8.org/btopallvote/0/570.htm", "http://www.bxwx8.org/btopallvote/0/571.htm",
                "http://www.bxwx8.org/btopallvote/0/572.htm", "http://www.bxwx8.org/btopallvote/0/573.htm",
                "http://www.bxwx8.org/btopallvote/0/574.htm", "http://www.bxwx8.org/btopallvote/0/575.htm",
                "http://www.bxwx8.org/btopallvote/0/576.htm", "http://www.bxwx8.org/btopallvote/0/577.htm",
                "http://www.bxwx8.org/btopallvote/0/578.htm", "http://www.bxwx8.org/btopallvote/0/579.htm",
                "http://www.bxwx8.org/btopallvote/0/580.htm", "http://www.bxwx8.org/btopallvote/0/581.htm",
                "http://www.bxwx8.org/btopallvote/0/582.htm", "http://www.bxwx8.org/btopallvote/0/583.htm",
                "http://www.bxwx8.org/btopallvote/0/584.htm", "http://www.bxwx8.org/btopallvote/0/585.htm",
                "http://www.bxwx8.org/btopallvote/0/586.htm", "http://www.bxwx8.org/btopallvote/0/587.htm",
                "http://www.bxwx8.org/btopallvote/0/588.htm", "http://www.bxwx8.org/btopallvote/0/589.htm",
                "http://www.bxwx8.org/btopallvote/0/590.htm", "http://www.bxwx8.org/btopallvote/0/591.htm",
                "http://www.bxwx8.org/btopallvote/0/592.htm", "http://www.bxwx8.org/btopallvote/0/593.htm",
                "http://www.bxwx8.org/btopallvote/0/594.htm", "http://www.bxwx8.org/btopallvote/0/595.htm",
                "http://www.bxwx8.org/btopallvote/0/596.htm", "http://www.bxwx8.org/btopallvote/0/597.htm",
                "http://www.bxwx8.org/btopallvote/0/598.htm", "http://www.bxwx8.org/btopallvote/0/599.htm",
                "http://www.bxwx8.org/btopallvote/0/600.htm", "http://www.bxwx8.org/btopallvote/0/601.htm",
                "http://www.bxwx8.org/btopallvote/0/602.htm", "http://www.bxwx8.org/btopallvote/0/603.htm",
                "http://www.bxwx8.org/btopallvote/0/604.htm", "http://www.bxwx8.org/btopallvote/0/605.htm",
                "http://www.bxwx8.org/btopallvote/0/606.htm", "http://www.bxwx8.org/btopallvote/0/607.htm",
                "http://www.bxwx8.org/btopallvote/0/608.htm", "http://www.bxwx8.org/btopallvote/0/609.htm",
                "http://www.bxwx8.org/btopallvote/0/610.htm", "http://www.bxwx8.org/btopallvote/0/611.htm",
                "http://www.bxwx8.org/btopallvote/0/612.htm", "http://www.bxwx8.org/btopallvote/0/613.htm",
                "http://www.bxwx8.org/btopallvote/0/614.htm", "http://www.bxwx8.org/btopallvote/0/615.htm",
                "http://www.bxwx8.org/btopallvote/0/616.htm", "http://www.bxwx8.org/btopallvote/0/617.htm",
                "http://www.bxwx8.org/btopallvote/0/618.htm", "http://www.bxwx8.org/btopallvote/0/619.htm",
                "http://www.bxwx8.org/btopallvote/0/620.htm", "http://www.bxwx8.org/btopallvote/0/621.htm",
                "http://www.bxwx8.org/btopallvote/0/622.htm", "http://www.bxwx8.org/btopallvote/0/623.htm",
                "http://www.bxwx8.org/btopallvote/0/624.htm", "http://www.bxwx8.org/btopallvote/0/625.htm",
                "http://www.bxwx8.org/btopallvote/0/626.htm", "http://www.bxwx8.org/btopallvote/0/627.htm",
                "http://www.bxwx8.org/btopallvote/0/628.htm", "http://www.bxwx8.org/btopallvote/0/629.htm",
                "http://www.bxwx8.org/btopallvote/0/630.htm", "http://www.bxwx8.org/btopallvote/0/631.htm",
                "http://www.bxwx8.org/btopallvote/0/632.htm", "http://www.bxwx8.org/btopallvote/0/633.htm",
                "http://www.bxwx8.org/btopallvote/0/634.htm", "http://www.bxwx8.org/btopallvote/0/635.htm",
                "http://www.bxwx8.org/btopallvote/0/636.htm", "http://www.bxwx8.org/btopallvote/0/637.htm",
                "http://www.bxwx8.org/btopallvote/0/638.htm", "http://www.bxwx8.org/btopallvote/0/639.htm",
                "http://www.bxwx8.org/btopallvote/0/640.htm", "http://www.bxwx8.org/btopallvote/0/641.htm",
                "http://www.bxwx8.org/btopallvote/0/642.htm", "http://www.bxwx8.org/btopallvote/0/643.htm",
                "http://www.bxwx8.org/btopallvote/0/644.htm", "http://www.bxwx8.org/btopallvote/0/645.htm",
                "http://www.bxwx8.org/btopallvote/0/646.htm", "http://www.bxwx8.org/btopallvote/0/647.htm",
                "http://www.bxwx8.org/btopallvote/0/648.htm", "http://www.bxwx8.org/btopallvote/0/649.htm",
                "http://www.bxwx8.org/btopallvote/0/650.htm", "http://www.bxwx8.org/btopallvote/0/651.htm",
                "http://www.bxwx8.org/btopallvote/0/652.htm", "http://www.bxwx8.org/btopallvote/0/653.htm",
                "http://www.bxwx8.org/btopallvote/0/654.htm", "http://www.bxwx8.org/btopallvote/0/655.htm",
                "http://www.bxwx8.org/btopallvote/0/656.htm", "http://www.bxwx8.org/btopallvote/0/657.htm",
                "http://www.bxwx8.org/btopallvote/0/658.htm", "http://www.bxwx8.org/btopallvote/0/659.htm",
                "http://www.bxwx8.org/btopallvote/0/660.htm", "http://www.bxwx8.org/btopallvote/0/661.htm",
                "http://www.bxwx8.org/btopallvote/0/662.htm", "http://www.bxwx8.org/btopallvote/0/663.htm",
                "http://www.bxwx8.org/btopallvote/0/664.htm", "http://www.bxwx8.org/btopallvote/0/665.htm",
                "http://www.bxwx8.org/btopallvote/0/666.htm", "http://www.bxwx8.org/btopallvote/0/667.htm",
                "http://www.bxwx8.org/btopallvote/0/668.htm", "http://www.bxwx8.org/btopallvote/0/669.htm",
                "http://www.bxwx8.org/btopallvote/0/670.htm", "http://www.bxwx8.org/btopallvote/0/671.htm",
                "http://www.bxwx8.org/btopallvote/0/672.htm", "http://www.bxwx8.org/btopallvote/0/673.htm",
                "http://www.bxwx8.org/btopallvote/0/674.htm", "http://www.bxwx8.org/btopallvote/0/675.htm",
                "http://www.bxwx8.org/btopallvote/0/676.htm", "http://www.bxwx8.org/btopallvote/0/677.htm",
                "http://www.bxwx8.org/btopallvote/0/678.htm", "http://www.bxwx8.org/btopallvote/0/679.htm",
                "http://www.bxwx8.org/btopallvote/0/680.htm", "http://www.bxwx8.org/btopallvote/0/681.htm",
                "http://www.bxwx8.org/btopallvote/0/682.htm", "http://www.bxwx8.org/btopallvote/0/683.htm",
                "http://www.bxwx8.org/btopallvote/0/684.htm", "http://www.bxwx8.org/btopallvote/0/685.htm",
                "http://www.bxwx8.org/btopallvote/0/686.htm", "http://www.bxwx8.org/btopallvote/0/687.htm",
                "http://www.bxwx8.org/btopallvote/0/688.htm", "http://www.bxwx8.org/btopallvote/0/689.htm",
                "http://www.bxwx8.org/btopallvote/0/690.htm", "http://www.bxwx8.org/btopallvote/0/691.htm",
                "http://www.bxwx8.org/btopallvote/0/692.htm", "http://www.bxwx8.org/btopallvote/0/693.htm",
                "http://www.bxwx8.org/btopallvote/0/694.htm", "http://www.bxwx8.org/btopallvote/0/695.htm",
                "http://www.bxwx8.org/btopallvote/0/696.htm", "http://www.bxwx8.org/btopallvote/0/697.htm",
                "http://www.bxwx8.org/btopallvote/0/698.htm", "http://www.bxwx8.org/btopallvote/0/699.htm",
                "http://www.bxwx8.org/btopallvote/0/700.htm", "http://www.bxwx8.org/btopallvote/0/701.htm",
                "http://www.bxwx8.org/btopallvote/0/702.htm", "http://www.bxwx8.org/btopallvote/0/703.htm",
                "http://www.bxwx8.org/btopallvote/0/704.htm", "http://www.bxwx8.org/btopallvote/0/705.htm",
                "http://www.bxwx8.org/btopallvote/0/706.htm", "http://www.bxwx8.org/btopallvote/0/707.htm",
                "http://www.bxwx8.org/btopallvote/0/708.htm", "http://www.bxwx8.org/btopallvote/0/709.htm",
                "http://www.bxwx8.org/btopallvote/0/710.htm", "http://www.bxwx8.org/btopallvote/0/711.htm",
                "http://www.bxwx8.org/btopallvote/0/712.htm", "http://www.bxwx8.org/btopallvote/0/713.htm",
                "http://www.bxwx8.org/btopallvote/0/714.htm", "http://www.bxwx8.org/btopallvote/0/715.htm",
                "http://www.bxwx8.org/btopallvote/0/716.htm", "http://www.bxwx8.org/btopallvote/0/717.htm",
                "http://www.bxwx8.org/btopallvote/0/718.htm", "http://www.bxwx8.org/btopallvote/0/719.htm",
                "http://www.bxwx8.org/btopallvote/0/720.htm", "http://www.bxwx8.org/btopallvote/0/721.htm",
                "http://www.bxwx8.org/btopallvote/0/722.htm", "http://www.bxwx8.org/btopallvote/0/723.htm",
                "http://www.bxwx8.org/btopallvote/0/724.htm", "http://www.bxwx8.org/btopallvote/0/725.htm",
                "http://www.bxwx8.org/btopallvote/0/726.htm", "http://www.bxwx8.org/btopallvote/0/727.htm",
                "http://www.bxwx8.org/btopallvote/0/728.htm", "http://www.bxwx8.org/btopallvote/0/729.htm",
                "http://www.bxwx8.org/btopallvote/0/730.htm", "http://www.bxwx8.org/btopallvote/0/731.htm",
                "http://www.bxwx8.org/btopallvote/0/732.htm", "http://www.bxwx8.org/btopallvote/0/733.htm",
                "http://www.bxwx8.org/btopallvote/0/734.htm", "http://www.bxwx8.org/btopallvote/0/735.htm",
                "http://www.bxwx8.org/btopallvote/0/736.htm", "http://www.bxwx8.org/btopallvote/0/737.htm",
                "http://www.bxwx8.org/btopallvote/0/738.htm", "http://www.bxwx8.org/btopallvote/0/739.htm",
                "http://www.bxwx8.org/btopallvote/0/740.htm", "http://www.bxwx8.org/btopallvote/0/741.htm",
                "http://www.bxwx8.org/btopallvote/0/742.htm", "http://www.bxwx8.org/btopallvote/0/743.htm",
                "http://www.bxwx8.org/btopallvote/0/744.htm", "http://www.bxwx8.org/btopallvote/0/745.htm",
                "http://www.bxwx8.org/btopallvote/0/746.htm", "http://www.bxwx8.org/btopallvote/0/747.htm",
                "http://www.bxwx8.org/btopallvote/0/748.htm", "http://www.bxwx8.org/btopallvote/0/749.htm",
                "http://www.bxwx8.org/btopallvote/0/750.htm", "http://www.bxwx8.org/btopallvote/0/751.htm",
                "http://www.bxwx8.org/btopallvote/0/752.htm", "http://www.bxwx8.org/btopallvote/0/753.htm",
                "http://www.bxwx8.org/btopallvote/0/754.htm", "http://www.bxwx8.org/btopallvote/0/755.htm",
                "http://www.bxwx8.org/btopallvote/0/756.htm", "http://www.bxwx8.org/btopallvote/0/757.htm",
                "http://www.bxwx8.org/btopallvote/0/758.htm", "http://www.bxwx8.org/btopallvote/0/759.htm",
                "http://www.bxwx8.org/btopallvote/0/760.htm", "http://www.bxwx8.org/btopallvote/0/761.htm",
                "http://www.bxwx8.org/btopallvote/0/762.htm", "http://www.bxwx8.org/btopallvote/0/763.htm",
                "http://www.bxwx8.org/btopallvote/0/764.htm", "http://www.bxwx8.org/btopallvote/0/765.htm",
                "http://www.bxwx8.org/btopallvote/0/766.htm", "http://www.bxwx8.org/btopallvote/0/767.htm",
                "http://www.bxwx8.org/btopallvote/0/768.htm", "http://www.bxwx8.org/btopallvote/0/769.htm",
                "http://www.bxwx8.org/btopallvote/0/770.htm", "http://www.bxwx8.org/btopallvote/0/771.htm",
                "http://www.bxwx8.org/btopallvote/0/772.htm", "http://www.bxwx8.org/btopallvote/0/773.htm",
                "http://www.bxwx8.org/btopallvote/0/774.htm", "http://www.bxwx8.org/btopallvote/0/775.htm",
                "http://www.bxwx8.org/btopallvote/0/776.htm", "http://www.bxwx8.org/btopallvote/0/777.htm",
                "http://www.bxwx8.org/btopallvote/0/778.htm", "http://www.bxwx8.org/btopallvote/0/779.htm",
                "http://www.bxwx8.org/btopallvote/0/780.htm", "http://www.bxwx8.org/btopallvote/0/781.htm",
                "http://www.bxwx8.org/btopallvote/0/782.htm", "http://www.bxwx8.org/btopallvote/0/783.htm",
                "http://www.bxwx8.org/btopallvote/0/784.htm", "http://www.bxwx8.org/btopallvote/0/785.htm",
                "http://www.bxwx8.org/btopallvote/0/786.htm", "http://www.bxwx8.org/btopallvote/0/787.htm",
                "http://www.bxwx8.org/btopallvote/0/788.htm", "http://www.bxwx8.org/btopallvote/0/789.htm",
                "http://www.bxwx8.org/btopallvote/0/790.htm", "http://www.bxwx8.org/btopallvote/0/791.htm",
                "http://www.bxwx8.org/btopallvote/0/792.htm", "http://www.bxwx8.org/btopallvote/0/793.htm",
                "http://www.bxwx8.org/btopallvote/0/794.htm", "http://www.bxwx8.org/btopallvote/0/795.htm",
                "http://www.bxwx8.org/btopallvote/0/796.htm", "http://www.bxwx8.org/btopallvote/0/797.htm",
                "http://www.bxwx8.org/btopallvote/0/798.htm", "http://www.bxwx8.org/btopallvote/0/799.htm",
                "http://www.bxwx8.org/btopallvote/0/800.htm", "http://www.bxwx8.org/btopallvote/0/801.htm",
                "http://www.bxwx8.org/btopallvote/0/802.htm", "http://www.bxwx8.org/btopallvote/0/803.htm",
                "http://www.bxwx8.org/btopallvote/0/804.htm", "http://www.bxwx8.org/btopallvote/0/805.htm",
                "http://www.bxwx8.org/btopallvote/0/806.htm", "http://www.bxwx8.org/btopallvote/0/807.htm",
                "http://www.bxwx8.org/btopallvote/0/808.htm", "http://www.bxwx8.org/btopallvote/0/809.htm",
                "http://www.bxwx8.org/btopallvote/0/810.htm", "http://www.bxwx8.org/btopallvote/0/811.htm",
                "http://www.bxwx8.org/btopallvote/0/812.htm", "http://www.bxwx8.org/btopallvote/0/813.htm",
                "http://www.bxwx8.org/btopallvote/0/814.htm", "http://www.bxwx8.org/btopallvote/0/815.htm",
                "http://www.bxwx8.org/btopallvote/0/816.htm", "http://www.bxwx8.org/btopallvote/0/817.htm",
                "http://www.bxwx8.org/btopallvote/0/818.htm", "http://www.bxwx8.org/btopallvote/0/819.htm",
                "http://www.bxwx8.org/btopallvote/0/820.htm", "http://www.bxwx8.org/btopallvote/0/821.htm",
                "http://www.bxwx8.org/btopallvote/0/822.htm", "http://www.bxwx8.org/btopallvote/0/823.htm",
                "http://www.bxwx8.org/btopallvote/0/824.htm", "http://www.bxwx8.org/btopallvote/0/825.htm",
                "http://www.bxwx8.org/btopallvote/0/826.htm", "http://www.bxwx8.org/btopallvote/0/827.htm",
                "http://www.bxwx8.org/btopallvote/0/828.htm", "http://www.bxwx8.org/btopallvote/0/829.htm",
                "http://www.bxwx8.org/btopallvote/0/830.htm", "http://www.bxwx8.org/btopallvote/0/831.htm",
                "http://www.bxwx8.org/btopallvote/0/832.htm", "http://www.bxwx8.org/btopallvote/0/833.htm",
                "http://www.bxwx8.org/btopallvote/0/834.htm", "http://www.bxwx8.org/btopallvote/0/835.htm",
                "http://www.bxwx8.org/btopallvote/0/836.htm", "http://www.bxwx8.org/btopallvote/0/837.htm",
                "http://www.bxwx8.org/btopallvote/0/838.htm", "http://www.bxwx8.org/btopallvote/0/839.htm",
                "http://www.bxwx8.org/btopallvote/0/840.htm", "http://www.bxwx8.org/btopallvote/0/841.htm",
                "http://www.bxwx8.org/btopallvote/0/842.htm", "http://www.bxwx8.org/btopallvote/0/843.htm",
                "http://www.bxwx8.org/btopallvote/0/844.htm", "http://www.bxwx8.org/btopallvote/0/845.htm",
                "http://www.bxwx8.org/btopallvote/0/846.htm", "http://www.bxwx8.org/btopallvote/0/847.htm",
                "http://www.bxwx8.org/btopallvote/0/848.htm", "http://www.bxwx8.org/btopallvote/0/849.htm",
                "http://www.bxwx8.org/btopallvote/0/850.htm", "http://www.bxwx8.org/btopallvote/0/851.htm",
                "http://www.bxwx8.org/btopallvote/0/852.htm", "http://www.bxwx8.org/btopallvote/0/853.htm",
                "http://www.bxwx8.org/btopallvote/0/854.htm", "http://www.bxwx8.org/btopallvote/0/855.htm",
                "http://www.bxwx8.org/btopallvote/0/856.htm", "http://www.bxwx8.org/btopallvote/0/857.htm",
                "http://www.bxwx8.org/btopallvote/0/858.htm", "http://www.bxwx8.org/btopallvote/0/859.htm",
                "http://www.bxwx8.org/btopallvote/0/860.htm", "http://www.bxwx8.org/btopallvote/0/861.htm",
                "http://www.bxwx8.org/btopallvote/0/862.htm", "http://www.bxwx8.org/btopallvote/0/863.htm",
                "http://www.bxwx8.org/btopallvote/0/864.htm", "http://www.bxwx8.org/btopallvote/0/865.htm",
                "http://www.bxwx8.org/btopallvote/0/866.htm", "http://www.bxwx8.org/btopallvote/0/867.htm",
                "http://www.bxwx8.org/btopallvote/0/868.htm", "http://www.bxwx8.org/btopallvote/0/869.htm",
                "http://www.bxwx8.org/btopallvote/0/870.htm", "http://www.bxwx8.org/btopallvote/0/871.htm",
                "http://www.bxwx8.org/btopallvote/0/872.htm", "http://www.bxwx8.org/btopallvote/0/873.htm",
                "http://www.bxwx8.org/btopallvote/0/874.htm", "http://www.bxwx8.org/btopallvote/0/875.htm",
                "http://www.bxwx8.org/btopallvote/0/876.htm", "http://www.bxwx8.org/btopallvote/0/877.htm",
                "http://www.bxwx8.org/btopallvote/0/878.htm", "http://www.bxwx8.org/btopallvote/0/879.htm",
                "http://www.bxwx8.org/btopallvote/0/880.htm", "http://www.bxwx8.org/btopallvote/0/881.htm",
                "http://www.bxwx8.org/btopallvote/0/882.htm", "http://www.bxwx8.org/btopallvote/0/883.htm",
                "http://www.bxwx8.org/btopallvote/0/884.htm", "http://www.bxwx8.org/btopallvote/0/885.htm",
                "http://www.bxwx8.org/btopallvote/0/886.htm", "http://www.bxwx8.org/btopallvote/0/887.htm",
                "http://www.bxwx8.org/btopallvote/0/888.htm", "http://www.bxwx8.org/btopallvote/0/889.htm",
                "http://www.bxwx8.org/btopallvote/0/890.htm", "http://www.bxwx8.org/btopallvote/0/891.htm",
                "http://www.bxwx8.org/btopallvote/0/892.htm", "http://www.bxwx8.org/btopallvote/0/893.htm",
                "http://www.bxwx8.org/btopallvote/0/894.htm", "http://www.bxwx8.org/btopallvote/0/895.htm",
                "http://www.bxwx8.org/btopallvote/0/896.htm", "http://www.bxwx8.org/btopallvote/0/897.htm",
                "http://www.bxwx8.org/btopallvote/0/898.htm", "http://www.bxwx8.org/btopallvote/0/899.htm",
                "http://www.bxwx8.org/btopallvote/0/900.htm", "http://www.bxwx8.org/btopallvote/0/901.htm",
                "http://www.bxwx8.org/btopallvote/0/902.htm", "http://www.bxwx8.org/btopallvote/0/903.htm",
                "http://www.bxwx8.org/btopallvote/0/904.htm", "http://www.bxwx8.org/btopallvote/0/905.htm",
                "http://www.bxwx8.org/btopallvote/0/906.htm", "http://www.bxwx8.org/btopallvote/0/907.htm",
                "http://www.bxwx8.org/btopallvote/0/908.htm", "http://www.bxwx8.org/btopallvote/0/909.htm",
                "http://www.bxwx8.org/btopallvote/0/910.htm", "http://www.bxwx8.org/btopallvote/0/911.htm",
                "http://www.bxwx8.org/btopallvote/0/912.htm", "http://www.bxwx8.org/btopallvote/0/913.htm",
                "http://www.bxwx8.org/btopallvote/0/914.htm", "http://www.bxwx8.org/btopallvote/0/915.htm",
                "http://www.bxwx8.org/btopallvote/0/916.htm", "http://www.bxwx8.org/btopallvote/0/917.htm",
                "http://www.bxwx8.org/btopallvote/0/918.htm", "http://www.bxwx8.org/btopallvote/0/919.htm",
                "http://www.bxwx8.org/btopallvote/0/920.htm", "http://www.bxwx8.org/btopallvote/0/921.htm",
                "http://www.bxwx8.org/btopallvote/0/922.htm", "http://www.bxwx8.org/btopallvote/0/923.htm",
                "http://www.bxwx8.org/btopallvote/0/924.htm", "http://www.bxwx8.org/btopallvote/0/925.htm",
                "http://www.bxwx8.org/btopallvote/0/926.htm", "http://www.bxwx8.org/btopallvote/0/927.htm",
                "http://www.bxwx8.org/btopallvote/0/928.htm", "http://www.bxwx8.org/btopallvote/0/929.htm",
                "http://www.bxwx8.org/btopallvote/0/930.htm", "http://www.bxwx8.org/btopallvote/0/931.htm",
                "http://www.bxwx8.org/btopallvote/0/932.htm", "http://www.bxwx8.org/btopallvote/0/933.htm",
                "http://www.bxwx8.org/btopallvote/0/934.htm", "http://www.bxwx8.org/btopallvote/0/935.htm",
                "http://www.bxwx8.org/btopallvote/0/936.htm", "http://www.bxwx8.org/btopallvote/0/937.htm",
                "http://www.bxwx8.org/btopallvote/0/938.htm", "http://www.bxwx8.org/btopallvote/0/939.htm",
                "http://www.bxwx8.org/btopallvote/0/940.htm", "http://www.bxwx8.org/btopallvote/0/941.htm",
                "http://www.bxwx8.org/btopallvote/0/942.htm", "http://www.bxwx8.org/btopallvote/0/943.htm",
                "http://www.bxwx8.org/btopallvote/0/944.htm", "http://www.bxwx8.org/btopallvote/0/945.htm",
                "http://www.bxwx8.org/btopallvote/0/946.htm", "http://www.bxwx8.org/btopallvote/0/947.htm",
                "http://www.bxwx8.org/btopallvote/0/948.htm", "http://www.bxwx8.org/btopallvote/0/949.htm",
                "http://www.bxwx8.org/btopallvote/0/950.htm", "http://www.bxwx8.org/btopallvote/0/951.htm",
                "http://www.bxwx8.org/btopallvote/0/952.htm", "http://www.bxwx8.org/btopallvote/0/953.htm",
                "http://www.bxwx8.org/btopallvote/0/954.htm", "http://www.bxwx8.org/btopallvote/0/955.htm",
                "http://www.bxwx8.org/btopallvote/0/956.htm", "http://www.bxwx8.org/btopallvote/0/957.htm",
                "http://www.bxwx8.org/btopallvote/0/958.htm", "http://www.bxwx8.org/btopallvote/0/959.htm",
                "http://www.bxwx8.org/btopallvote/0/960.htm", "http://www.bxwx8.org/btopallvote/0/961.htm",
                "http://www.bxwx8.org/btopallvote/0/962.htm", "http://www.bxwx8.org/btopallvote/0/963.htm",
                "http://www.bxwx8.org/btopallvote/0/964.htm", "http://www.bxwx8.org/btopallvote/0/965.htm",
                "http://www.bxwx8.org/btopallvote/0/966.htm", "http://www.bxwx8.org/btopallvote/0/967.htm",
                "http://www.bxwx8.org/btopallvote/0/968.htm", "http://www.bxwx8.org/btopallvote/0/969.htm",
                "http://www.bxwx8.org/btopallvote/0/970.htm", "http://www.bxwx8.org/btopallvote/0/971.htm",
                "http://www.bxwx8.org/btopallvote/0/972.htm", "http://www.bxwx8.org/btopallvote/0/973.htm",
                "http://www.bxwx8.org/btopallvote/0/974.htm", "http://www.bxwx8.org/btopallvote/0/975.htm",
                "http://www.bxwx8.org/btopallvote/0/976.htm", "http://www.bxwx8.org/btopallvote/0/977.htm",
                "http://www.bxwx8.org/btopallvote/0/978.htm", "http://www.bxwx8.org/btopallvote/0/979.htm",
                "http://www.bxwx8.org/btopallvote/0/980.htm", "http://www.bxwx8.org/btopallvote/0/981.htm",
                "http://www.bxwx8.org/btopallvote/0/982.htm", "http://www.bxwx8.org/btopallvote/0/983.htm",
                "http://www.bxwx8.org/btopallvote/0/984.htm", "http://www.bxwx8.org/btopallvote/0/985.htm",
                "http://www.bxwx8.org/btopallvote/0/986.htm", "http://www.bxwx8.org/btopallvote/0/987.htm",
                "http://www.bxwx8.org/btopallvote/0/988.htm", "http://www.bxwx8.org/btopallvote/0/989.htm",
                "http://www.bxwx8.org/btopallvote/0/990.htm", "http://www.bxwx8.org/btopallvote/0/991.htm",
                "http://www.bxwx8.org/btopallvote/0/992.htm", "http://www.bxwx8.org/btopallvote/0/993.htm",
                "http://www.bxwx8.org/btopallvote/0/994.htm", "http://www.bxwx8.org/btopallvote/0/995.htm",
                "http://www.bxwx8.org/btopallvote/0/996.htm", "http://www.bxwx8.org/btopallvote/0/997.htm",
                "http://www.bxwx8.org/btopallvote/0/998.htm", "http://www.bxwx8.org/btopallvote/0/999.htm" };
        List<StorySeed> list = new ArrayList<StorySeed>();
        for (String url : urls) {
            List<StorySeed> storySeedList = buildStorySeed(url);
            if (storySeedList != null && storySeedList.size() > 0) {
                list.addAll(storySeedList);
            }
        }

        StorySeedService.saveFile(list);
    }

    public static List<StorySeed> buildStorySeed(String url) {
        try {

            WebClientPool webClientPool = new WebClientPool();
            final HtmlPage htmlpage = webClientPool.borrowWebClient().getPage(url);
            List<HtmlAnchor> anchorList = (List<HtmlAnchor>) htmlpage
                    .getByXPath("//div[@id='centerm']/table/tbody/tr/td[1]/a");
            List<StorySeed> seedList = new ArrayList<StorySeed>();
            if (anchorList != null && anchorList.size() > 0) {
                String href = "";
                for (HtmlAnchor htmlAnchor : anchorList) {
                    System.out.println(htmlAnchor.getTextContent() + " url=" + htmlAnchor.getAttribute("href"));

                    href = "http://www.bxwx8.org" + htmlAnchor.getAttribute("href");
                    if (href != null) {
                        Integer categoryId = null;
                        try {
                            Thread.sleep(2000);
                            HtmlPage page = webClientPool.borrowWebClient().getPage(href);
                            categoryId = getCategoryId(page);
                        } catch (Exception e) {
                        }

                        if (categoryId != null) {
                            seedList.add(new StorySeed(htmlAnchor.getTextContent().replace("下载", "").trim(), categoryId
                                    + "", "22", href, ""));
                        }
                    }
                }
            }
            return seedList;
        } catch (FailingHttpStatusCodeException e) {
            e.printStackTrace();
        } catch (MalformedURLException e) {
            e.printStackTrace();
        } catch (ElementNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }

    public static Integer getCategoryId(HtmlPage page) {
        java.util.List elementList = (java.util.List) page
                .getByXPath("//div[@id='centerm']/table[1]/tbody/tr/td/table[1]/tbody/tr/td/font/a[2]");
        java.lang.Integer ret = null;

        if (elementList != null && elementList.size() > 0) {
            com.gargoylesoftware.htmlunit.html.HtmlElement element = (com.gargoylesoftware.htmlunit.html.HtmlElement) elementList
                    .get(0);

            String categoryName = element.getTextContent();
            categoryName = categoryName.trim();
            if ("玄幻魔法".equals(categoryName)) {
                ret = 30;
            } else if ("武侠修真".equals(categoryName)) {
                ret = 29;
            } else if ("历史军事".equals(categoryName)) {
                ret = 27;
            } else if ("现代都市".equals(categoryName)) {
                ret = 28;
            } else if ("游戏竞技".equals(categoryName)) {
                ret = 26;
            } else if ("科幻灵异 ".equals(categoryName)) {
                ret = 25;
            } else if ("言情小说 ".equals(categoryName)) {
                ret = 28;
            } else if ("耽美小说 ".equals(categoryName)) {
                ret = 41;
            } else if ("同人小说 ".equals(categoryName)) {
                ret = 41;
            }
            return ret;
        }

        return ret;
    }

}
